# theme: jekyll-text-theme
remote_theme: kitian616/jekyll-TeXt-theme
text_skin: default
highlight_theme: tomorrow-night
url     : 
baseurl : 
title   : Keinoki 的博客
description: >
  You see see you. 


lang: zh-Hans
timezone: Asia/Shanghai


author:
  type      : person
  name      : keinoki
  url       : https://github.com/keinoki
  avatar    : 
  email     : ikoniek@outlook.com
  github    : keinoki
  start_working_date: 2019-7


repository: keinoki/keinoki.github.io
repository_tree: master

paths:
  root    : /
  home    : /
  archive : /archive.html
  rss     : /feed.xml

excerpt_separator: <!--more-->

license: CC-BY-NC-4.0

toc:
  selectors: h1,h2,h3

mathjax: false
mathjax_autoNumber: false

mermaid: false

chart: false

paginate: 10
paginate_path: /page:num

sources: bootcdn

comments:
  provider: disqus

  disqus:
    shortname: keyiyin


search:
  provider: default

analytics:
  provider: false

markdown    : kramdown
highlighter : rouge
permalink   : date

kramdown:
  input: GFM

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: true
      license: true
      aside:
        toc: true
      show_edit_on_github: true
      show_subscribe: true
      pageview: true

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
  - jekyll-remote-theme
